### PR TITLE
fix(select): Fixed nested labelField and valueField error

### PR DESCRIPTION
**Pull request by darckoune**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/edcarroll/ng2-semantic-ui/blob/master/CONTRIBUTING.md#) guide.
 - [x] linted, built and tested the changes locally.
 - [x] added/updated any applicable API documentation. (nothing to do)
 - [x] added/updated any applicable demos. (nothing to do)

Solves #381

### CODE REVIEW

**Comment by edcarroll** [comment]
Thank you for the PR 🎉 

Will get this looked at and hopefully merged next week.

**Comment by edcarroll** [comment]
Thank you for the PR 🎉 

Will get this looked at and hopefully merged next week.

**Comment by edcarroll** [comment]
Thank you again for this fix. Will be cutting a new next version soon, and it will be live properly in the next release.

**Comment by darckoune** [comment]
No problem. Thank you for your work on this repo :)

**Pull request merged**
