### PR TITLE
feat: Add dropdown and select hover open and close functionality

### PR DESCRIPTION
**Pull request by trevordaniels**
This first commit only adds functionality to dropdown, not select, and its not linted yet. I'm after feedback on this approach before continuing. 

I moved some methods into dropdown service so they can potentially be re-used by select.

### CODE REVIEW

**Comment by edcarroll** [comment]
This approach looks good, my only major sticking point is that currently the dropdown service purposefully avoids any code that handles DOM interaction or transitions. This is because the dropdown menu has been able to process most of that stuff, and the search & select components don't really leverage any functionality that isn't in the menu.

Though, you mention adding the hover stuff to the select - though I'm not sure how well that fits in with the idea of the component if you see what I mean?

**Comment by edcarroll** [comment]
One other thing sorry, could you target the `v0.10.0` branch with this PR please? Since it's a breaking change once it's merged it's best to not have it conflict with master

**Comment by edcarroll** [comment]
Another thought I've just had - I wonder if this could be generalized into a completely separate service, that takes the configuration options and events and spits out open and close events as required?

We could then use it in the popup component pretty easily, as well as parts of it for the select e.t.c as required.

Thoughts?

**Comment by trevordaniels** [comment]
Sounds good, makes sense to pull out duplicate logic and put it into a shared service. And have one shared OpenTriggerType, and CloseTriggerType? I'll put together an initial attempt at this if you like, feel free to weigh in with interfaces, types etc.

**Pull request closed without merging**
