### PR TITLE
feat: Add hover trigger to select and dropdown

### PR DESCRIPTION
**Pull request by trevordaniels**
A new 'trigger' setting for select and dropdown which defaults to 'click', but also can be 'hover'.

Includes a 100ms hover delay.

### CODE REVIEW

**Comment by edcarroll** [comment]
Thank you for the PR 😄 So I had a think about this when it was brought up in #199, as I feel it conflicts with the `autoClose` option for the dropdown (trigger `hover` autoClose `disabled`?).

On balance however, I feel that I may have been wrong, as you'd still want a dropdown that opened on hover to remain open until closed.

Thoughts?

**Comment by trevordaniels** [comment]
I found autoClose slightly confusing as itemClick and outsideClick aren't necessarily mutually exclusive options. Also the default 'click' close action is implicit, additional to this setting, and acts on the original dropdown button/label only, not the dropdown menu itself.

One suggestion is to make all close actions explicit by replacing/renaming autoClose and letting it accept an array of options eg.
```
openTrigger="click" [closeTriggers]=['click', 'itemClick', 'outsideClick']
openTrigger="hover" [closeTriggers]=['itemClick', 'outsideHover']
```
Disabled would no longer be a valid option, and default close triggers could be similar to above for each open trigger.

Item click to close could be pulled out into a new setting 
``` 
[closeOnItemClick]="true|false"
```
Alternatively, 'hover' trigger could by default mimic 'click' more directly and toggle visibility only with respect to events on the original target area, not the menu. This keeps autoClose as the close trigger specifically for events with respect to the menu.

Does any of that sense? :)

**Comment by edcarroll** [comment]
Briefly to explain, idea with `autoClose` was that each option added more than the previous, so `disabled` was the base option, then `outsideClick` added the ability to close when not clicking inside, then `itemClick` added closing when individual items were clicked. This is why they aren't mutually exclusive options as you mentioned.

What do you mean by the default `click` close action? In the dropdown case the default is `itemClick`.

I really like the idea of having an `openTrigger` and a `closeTrigger` - though I worry your proposed syntax is a bit complex to get what you want working (many people get confused about the bind syntax so adding an array literal in the mix may be a bit much). I wonder if the same idea I mentioned above (where each option is a strict superset of the previous) can be applied here?

Taking this idea further, perhaps we have:

`openTrigger` options: `manual` -> `click` -> `hover`
`closeTrigger` options: `manual` -> `outsideClick` -> `outsideHover` -> `itemClick`

Though, this does preclude being able to have the dropdown not close when you're hovering. However on balance that could be pretty annoying... Your suggestion of `closeOnItemClick` would alleviate that though, so perhaps that is the way to go?

Also, with hover, should the delay time be configurable?

**Comment by trevordaniels** [comment]
This makes sense with your explanation but I didnt find it clear from the option names. Maybe renaming 'itemClick' to 'outsideOrItemClick' would make it clearer.

By 'default `click` close option' I mean the ability to close the menu by clicking on the label/button that originally triggers the opening of the menu ie. the only way to close the menu when `autoClose = disabled`. Whatever `autoClose` is set to, the menu can always be closed by clicking on the label/button. This isn't actually specified anywhere when using the control, hence I refer to it as a default implicit action, and it is additional to any close option specified in `autoClose`.

The array syntax is a little confusing initially but no more so than specifying an options string array for eg.
```html
<sui-select [options]="['Orange','Blue','Green']"></sui-select>
```
I personally think this is the best way to go - every trigger is explicit, allows maximum flexibility and doesnt rely upon an implicit hierarchy. Having said that though, your hierarchy would work and benefits from simplicity as long as it meets all use cases and is explained in the docs. 

ItemClick does seem like the odd one out on those trigger hierarchies and could benefit from being its own setting. Even extended to be a customisable event? eg.
```js
// fire an event (similar to sem.ui core dropdown action)

(itemClick)="dropdown.close()|customMethod($event)"
```
This would allow dropdowns to be used to construct navigation menus with slightly more complex routing logic than could be specified in a routerLink attribute in the view.

Yes it's a good idea for the hover delay to be configurable.

**Comment by edcarroll** [comment]
I'm with you now regarding the 'default' close option. I'm coming around to the array option for `closeTrigger`, though perhaps we allow `string | string[]` - so if you only enter one option you can just write that single one?

I definitely agree that it gives the user the most flexibility, and that's really what we want in the end. One thing I've just though of - does `outsideHover` really make sense without `outsideClick`? As I think you'd always expect the dropdown to close on click if hover closing is also enabled.

Custom event is a good idea, though what would we pass as `$event`? The items aren't normally bound to anything.

**Comment by trevordaniels** [comment]
I like the idea of accepting a string as well as an array.

I think outside hover makes sense without outside click. As soon as you
hover out, the menu closes and outside click never gets a chance to fire
anyway.

You're right, there's nothing useful to supply in $event at the moment. I
have a use case where I need a navigation menu with some routing logic best
placed in code than the template. I thought hooking into one event on the
dropdown rather than individual click events on every item would be
cleaner. But it would necessitate adding some new value attribute or
directive to each item. Eg. `[dropdownValue]="login"

**Comment by edcarroll** [comment]
Though, the hover should have a closing delay as well - so there is the case of a click before the delay ends if you see what I mean?

I wonder though, would there be much harm in adding a directive like `suiDropdownItemValue` or something that can be attached at will? I mean tbh, you could just add `[value]` to the `suiDropdownItem` directive and it immediately will let you bind - since the dropdown binds to all `.item` elements.

So to sum up:

* Get rid of `autoClose`
* Add three properties
   * `openTrigger`
      * `string` (`| string[]` for consistency with `closeTrigger`?)
      * options: `hover`, `click`
      * default: `click`?
   * `closeTrigger`
      * `string | string[]`
      * options: `outsideHover`, `click`, `itemClick`, `outsideClick`
      * default: `[`click`, `outsideClick`, `itemClick`]`?
   * `hoverDelay`
      * `number`
      * default: `100`?

**Comment by trevordaniels** [comment]
oops, didnt mean for this to close. @edcarroll are you able to re-open or should I create a new PR?

**Comment by edcarroll** [comment]
@trevordaniels I don't seem to be able to reopen (I think because the branch was deleted) - please do make a new PR

**Pull request closed without merging**
